/**
 * 231. Power of Two
 * Given an integer n, return true if it is a power of two. Otherwise, return false.
 *
 * An integer n is a power of two, if there exists an integer x such that n == 2x.
 *
 *
 *
 * Example 1:
 *
 * Input: n = 1
 * Output: true
 * Explanation: 20 = 1
 * Example 2:
 *
 * Input: n = 16
 * Output: true
 * Explanation: 24 = 16
 * Example 3:
 *
 * Input: n = 3
 * Output: false
 *
 */
fun isPowerOfTwo(n: Int): Boolean {
    return (n > 0 && (n and (n - 1) == 0))
}

/**
 * 136. Single Number
 * Easy
 * Topics
 * premium lock icon
 * Companies
 * Hint
 * Given a non-empty array of integers nums, every element appears twice except for one. Find that single one.
 *
 * You must implement a solution with a linear runtime complexity and use only constant extra space.
 *
 *
 *
 * Example 1:
 *
 * Input: nums = [2,2,1]
 *
 * Output: 1
 *
 * Example 2:
 *
 * Input: nums = [4,1,2,1,2]
 *
 * Output: 4
 *
 * Example 3:
 *
 * Input: nums = [1]
 *
 * Output: 1
 */
fun singleNumber(nums: IntArray): Int {
    var result = 0
    for (i in nums) {
        result = result xor i
    }
    return result
}

/**
 * 389. Find the Difference
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Return the letter that was added to t.
 *
 *
 *
 * Example 1:
 *
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * Example 2:
 *
 * Input: s = "", t = "y"
 * Output: "y"
 */
fun findTheDifference(s: String, t: String): Char {
    var result = 0

    for (i in s) {
        result = result xor i.code
    }

    for (i in t) {
        result = result xor i.code
    }

    return result.toChar()
}

/**
 * 190. Reverse Bits
 * Reverse bits of a given 32 bits signed integer.
 *
 *
 *
 * Example 1:
 *
 * Input: n = 43261596
 *
 * Output: 964176192
 *
 * Explanation:
 *
 * Integer	Binary
 * 43261596	00000010100101000001111010011100
 * 964176192	00111001011110000010100101000000
 * Example 2:
 *
 * Input: n = 2147483644
 *
 * Output: 1073741822
 *
 * Explanation:
 *
 * Integer	Binary
 * 2147483644	01111111111111111111111111111100
 * 1073741822	00111111111111111111111111111110
 *
 */
fun reverseBits(n: Int): Int {
    var pr = n
    var result = 0
    for (i in 0..31) {
        result = result shl 1
        val bit = pr and 1
        pr = pr ushr 1
        result = result or bit
    }
    return result
}

/**
 * 191. Number of 1 Bits
 * Given a positive integer n, write a function that returns the number of set bits in its binary representation (also known as the Hamming weight).
 *
 *
 *
 * Example 1:
 *
 * Input: n = 11
 *
 * Output: 3
 *
 * Explanation:
 *
 * The input binary string 1011 has a total of three set bits.
 *
 * Example 2:
 *
 * Input: n = 128
 *
 * Output: 1
 *
 * Explanation:
 *
 * The input binary string 10000000 has a total of one set bit.
 *
 * Example 3:
 *
 * Input: n = 2147483645
 *
 * Output: 30
 *
 * Explanation:
 *
 * The input binary string 1111111111111111111111111111101 has a total of thirty set bits.
 */
fun hammingWeightEnumeration(n: Int): Int {
    var pr = n
    var count = 0
    for (i in 0..31) {
        if ((pr and 1) == 1) {
            count++
        }
        pr = pr ushr 1
    }
    return count
}

fun hammingWeight(n: Int): Int {
    var pr = n
    var count = 0
    while (pr!=0) {
        pr = pr and (pr-1)
        count++
    }
    return count
}