/**
 * 231. Power of Two
 * Given an integer n, return true if it is a power of two. Otherwise, return false.
 *
 * An integer n is a power of two, if there exists an integer x such that n == 2x.
 *
 *
 *
 * Example 1:
 *
 * Input: n = 1
 * Output: true
 * Explanation: 20 = 1
 * Example 2:
 *
 * Input: n = 16
 * Output: true
 * Explanation: 24 = 16
 * Example 3:
 *
 * Input: n = 3
 * Output: false
 *
 */
fun isPowerOfTwo(n: Int): Boolean {
    return (n > 0 && (n and (n - 1) == 0))
}

/**
 * 136. Single Number
 * Easy
 * Topics
 * premium lock icon
 * Companies
 * Hint
 * Given a non-empty array of integers nums, every element appears twice except for one. Find that single one.
 *
 * You must implement a solution with a linear runtime complexity and use only constant extra space.
 *
 *
 *
 * Example 1:
 *
 * Input: nums = [2,2,1]
 *
 * Output: 1
 *
 * Example 2:
 *
 * Input: nums = [4,1,2,1,2]
 *
 * Output: 4
 *
 * Example 3:
 *
 * Input: nums = [1]
 *
 * Output: 1
 */
fun singleNumber(nums: IntArray): Int {
    var result = 0
    for (i in nums) {
        result = result xor i
    }
    return result
}

/**
 * 389. Find the Difference
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Return the letter that was added to t.
 *
 *
 *
 * Example 1:
 *
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * Example 2:
 *
 * Input: s = "", t = "y"
 * Output: "y"
 */
fun findTheDifference(s: String, t: String): Char {
    var result = 0

    for (i in s) {
        result = result xor i.code
    }

    for (i in t) {
        result = result xor i.code
    }

    return result.toChar()
}